version: '3.9'

services:
  db_auth:
    image: postgres
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: postgres
    restart: always
